language: c
compiler:
           - gcc
           - clang

sudo: required
before_install:
        - sudo apt-get update -qq
        - sudo apt-get install libevent-dev libonig-dev
script:
        - cd build && cmake -DCMAKE_BUILD_TYPE=Debug .. && make examples

notifications:
        - irc "irc.oftc.net#libevhtp"
